const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function boot(){const c=vm.createContext({console,Response,Request,Headers,URL,setTimeout,clearTimeout});vm.runInContext(fs.readFileSync('src/worker.js','utf8').replace('export default','globalThis.worker='),c);return c}
const ref=JSON.parse(fs.readFileSync('tests/references/2026-10-01.json'));
test('October 1 benchmark keeps unresolved anchors visible instead of turning them into matches',()=>{let anchors=0,bands=0,n=0;const c=boot();for(const x of ref.cases){const j=JSON.parse(fs.readFileSync(`tests/fixtures/2026-10-01/${x.code}.json`));assert.equal(j.rows.at(-1).date,ref.baseDate);assert.ok(j.rows.every(r=>r.date<=ref.baseDate));c.rows=j.rows;const a=vm.runInContext('analyze(rows,"confluence")',c);for(const [k,e] of Object.entries(x.expected)){if(!e){assert.equal(a[k],null);continue}n++;if(a[k]?.price===e.price)anchors++;if(e.bandLow!=null&&a[k]?.bandLow===e.bandLow&&a[k]?.bandHigh===e.bandHigh)bands++}if(a.resistance2&&a.breakout)assert.ok(a.resistance2.bandLow>a.breakout.bandHigh)}assert.equal(n,35);assert.ok(anchors>=29);assert.ok(bands>=15);assert.ok(!('resistance2' in ref.cases.find(x=>x.code==='4919').expected))});
test('API retains real second pressure above breakout and date archive works with network unavailable',async()=>{const c=boot();c.assets={fetch:async req=>{const p='public'+new URL(req.url).pathname;return fs.existsSync(p)?new Response(fs.readFileSync(p)):new Response('',{status:404})}};vm.runInContext('resolve=async()=>({code:"2408",name:"南亞科",market:"TWSE"});history=async()=>{throw Error("network unavailable")}',c);const a=await vm.runInContext('analyzeOne("2408","2026-10-01","confluence",assets)',c);assert.equal(a.analysis.breakout.price,528);assert.equal(a.analysis.resistance1,null);assert.equal(a.analysis.resistance2.price,543);assert.equal(a.analysis.support2.bandLow,498);assert.equal(a.backtest.baseDate,'2026-10-01');assert.equal(a.backtest.actual,null);assert.match(a.source,/快照/);c.stock={code:'2408',market:'TWSE'};assert.equal(await vm.runInContext('archivedHistory(stock,"2026-10-02",assets,"confluence")',c),null)});
test('confluence renderer shows breakout and second independently, preserving old-mode display',()=>{const c=vm.createContext({console,clearTimeout,localStorage:{getItem:()=>null,setItem(){}},document:{querySelector:()=>null}});const s=fs.readFileSync('public/app.js','utf8');vm.runInContext(s.slice(0,s.indexOf('$("#analyze").onclick')),c);c.a={structurePolicy:{profile:'confluence'},breakout:{price:528,bandLow:522,bandHigh:533,sources:[]},resistance2:{price:543,bandLow:538,bandHigh:543,sources:[]}};const h=vm.runInContext('pressureLevels(a).join("")',c);assert.match(h,/第二壓力/);assert.match(h,/543/);assert.doesNotMatch(h,/第一壓力/)});
test('API estimate does not change when future OHLC is added to validation history',async()=>{const c=boot();c.rows=JSON.parse(fs.readFileSync('tests/fixtures/2026-10-01/1303.json')).rows;c.all=[...c.rows,{date:'2026-10-02',open:999,high:1000,low:900,close:999,volume:9999999}];vm.runInContext('resolve=async()=>({code:"1303",name:"南亞",market:"TWSE"});history=async()=>all',c);const a=await vm.runInContext('analyzeOne("1303","2026-10-01","confluence")',c);assert.equal(a.analysis.current,254);assert.equal(a.analysis.support1.bandLow,250);assert.equal(a.analysis.resistance1.price,255.5);assert.equal(a.backtest.actual.close,999);assert.ok(a.analysis.rows.every(r=>r.date<='2026-10-01'))});

test('historical pressure anchor remains stable when today high moves within its confirmed zone',()=>{const c=boot();for(const high of [31.6,31.7]){c.rows=JSON.parse(fs.readFileSync('tests/fixtures/2026-10-01/2371.json')).rows;c.rows.at(-1).high=high;const a=vm.runInContext('analyze(rows,"confluence")',c);assert.equal(a.resistance2.price,31.65);assert.ok(a.resistance2.bandLow<=a.resistance2.price&&a.resistance2.price<=a.resistance2.bandHigh);assert.ok(a.resistance2.bandLow>a.breakout.bandHigh)}
 c.rows=JSON.parse(fs.readFileSync('tests/fixtures/2026-10-01/2371.json')).rows;c.rows.find(r=>r.date==='2026-06-03').close=31.7;assert.equal(vm.runInContext('analyze(rows,"confluence").resistance2.price',c),31.7);
});
test('gap floor comes from confirmed swing evidence and changes when that evidence changes',()=>{const c=boot();c.rows=JSON.parse(fs.readFileSync('tests/fixtures/2026-10-01/3026.json')).rows;assert.equal(vm.runInContext('analyze(rows,"confluence").support1.bandLow',c),839);c.rows.find(r=>r.date==='2026-07-03').low=840;assert.equal(vm.runInContext('analyze(rows,"confluence").support1.bandLow',c),840)});
test('source audit keeps missing primary origins explicit and never calls them proven formulas',()=>{const r=JSON.parse(fs.readFileSync('public/calibration/2026-10-01.json'));assert.equal(r.sourceAudit.status,'hypotheses-only');assert.equal(r.sourceAudit.unresolved.length,9);for(const [code,price] of [['8358',484.5],['3026',850],['3026',919]]){const x=r.sourceAudit.unresolved.find(x=>x.code===code&&x.price===price);assert.equal(x.direct.length,0);assert.equal(x.adjusted.length,0);assert.equal(x.movingAverages.length,0)}assert.ok(r.sourceAudit.unresolved.some(x=>x.code==='3406'&&x.price===970&&x.direct.some(y=>y.date==='2026-09-08')))});
