const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function boot(){const ctx=vm.createContext({console,Response,Request,Headers,URL,setTimeout,clearTimeout});vm.runInContext(fs.readFileSync('src/worker.js','utf8').replace('export default','globalThis.worker='),ctx);return ctx}
const ref=JSON.parse(fs.readFileSync('tests/references/2026-10-05-extended.json'));
test('six reference cases match full bands and all four dagger annotations in both 182-day interpretations',()=>{for(const profile of ['extended-calendar','extended-sessions']){const ctx=boot();for(const item of ref.cases){const snap=JSON.parse(fs.readFileSync(`tests/fixtures/2026-10-05-extended/${item.code}.json`));assert.equal(snap.rows.at(-1).date,ref.baseDate);assert.ok(snap.rows.every(r=>r.date<=ref.baseDate));ctx.rows=snap.rows;ctx.adjustment=snap.adjustment;ctx.profile=profile;const a=vm.runInContext('analyze(rows,profile,adjustment)',ctx);for(const [key,e] of Object.entries(item.expected)){const p=a[key];if(!e){assert.equal(p,null,`${item.code} ${key}`);continue}assert.equal(p.bandLow,e.bandLow,`${profile} ${item.code} ${key} low`);assert.equal(p.bandHigh,e.bandHigh,`${profile} ${item.code} ${key} high`);assert.equal(p.latestCandleObservation,e.latestCandleObservation,`${item.code} ${key} dagger`)}if(a.support2)assert.ok(a.support2.bandHigh<a.support1.bandLow);if(a.resistance2)assert.ok(a.resistance2.bandLow>a.resistance1.bandHigh)}}});
test('ratio adjustment applies only to rows before events already effective at the estimate cutoff',()=>{const c=boot();c.rows=[{date:'2026-09-08',open:100,high:110,low:90,close:105,volume:1000},{date:'2026-10-05',open:100,high:110,low:90,close:105,volume:1000}];c.events=[{date:'2026-09-09',factor:.95},{date:'2026-10-06',factor:.5}];const r=vm.runInContext('adjustHistory(rows,events)',c);assert.equal(r[0].high,104.5);assert.equal(r[1].high,110);assert.equal(r[0].volume,1000);assert.equal(c.rows[0].high,110)});
test('official ex-rights parser accepts TWSE uppercase and TPEx lowercase successful status',()=>{const c=boot();c.j={stat:'ok',tables:[{data:[['115/09/09','1815','富喬','135.00','128.10']]}]};const events=vm.runInContext('parseCorporateActions(j,"TPEX")',c);assert.equal(events[0].date,'2026-09-09');assert.equal(events[0].factor,128.1/135);assert.equal(vm.runInContext('parseCorporateActions({stat:"error"},"TWSE")',c),null)});
test('live corporate actions failure uses validated coverage snapshot, not reference prices',async()=>{const c=boot();c.fetch=async url=>url.includes('/data/')?new Response(fs.readFileSync('public/data/ex-rights-2026-10-05.json')):new Response('{}',{status:503});const a=await vm.runInContext('corporateActions({code:"3044",market:"TWSE"},"2025-11-03","2026-10-05")',c);assert.equal(a.status,'verified-ex-rights-snapshot');assert.equal(a.events[0].factor,459.3/472);const b=await vm.runInContext('corporateActions({code:"3044",market:"TWSE"},"2025-11-03","2026-10-06")',c);assert.equal(b.status,'unavailable');assert.equal(b.events.length,0)});
test('extended API freezes future OHLC and ignores future corporate events',async()=>{const c=boot(),snapshot=JSON.parse(fs.readFileSync('tests/fixtures/2026-10-05-extended/3044.json'));c.fixture=[...snapshot.rows,{...snapshot.rows.at(-1),date:'2026-10-06',close:999,high:1000,low:900}];c.adjustment={...snapshot.adjustment,events:[...snapshot.adjustment.events,{date:'2026-10-06',factor:.1}]};vm.runInContext('resolve=async()=>({code:"3044",name:"健鼎",market:"TWSE"});history=async()=>fixture;corporateActions=async()=>adjustment',c);const a=await vm.runInContext('analyzeOne("3044","2026-10-05","extended-calendar")',c);assert.equal(a.analysis.current,557);assert.equal(a.analysis.resistance2.bandHigh,582);assert.equal(a.backtest.actual.close,999);assert.equal(a.backtest.noLookahead,true);assert.ok(a.analysis.rows.every(r=>r.date<='2026-10-05'));await assert.rejects(vm.runInContext('analyzeOne("3044","2026-10-05","not-a-model")',c),/無效/)});
test('UI uses dagger for latest observations and preserves gap-star semantics in standard levels',()=>{const c=vm.createContext({console,clearTimeout,localStorage:{getItem:()=>null,setItem(){}},document:{querySelector:()=>null}}),app=fs.readFileSync('public/app.js','utf8');vm.runInContext(app.slice(0,app.indexOf('$("#analyze").onclick')),c);c.levelData={price:564,bandLow:564,bandHigh:564,sources:[],marker:'†',latestCandleObservation:true};assert.match(vm.runInContext('level("第一壓力",levelData)',c),/564†/);c.levelData={price:5600,bandLow:5600,bandHigh:5600,sources:[],gapBoundary:true};assert.match(vm.runInContext('level("第二支撐",levelData)',c),/5,600＊/)});
