const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function boot(){const c=vm.createContext({console,Response,Request,URL,Headers,setTimeout});vm.runInContext(fs.readFileSync('src/worker.js','utf8').replace('export default','globalThis.worker='),c);return c}
const snapshot=JSON.parse(fs.readFileSync('public/data/chips/2026-10-06.json'));
test('all 19 official snapshots preserve gross buys/sells, category sums and margin balance identities',()=>{assert.equal(snapshot.items.length,19);const c=boot();for(const x of snapshot.items){c.o=x.institutional;c.mo=x.margin;const i=vm.runInContext('institutionalFrom(o)',c),m=vm.runInContext('marginFrom(mo)',c);assert.ok(i&&m,x.code);for(const g of Object.values(i.gross))assert.equal(g.buy-g.sell,g.net,x.code);assert.equal(i.foreignCombined+i.trust+i.dealer,i.total);assert.equal(m.marginPrevious+m.marginBuy-m.marginSell-m.marginRepay,m.marginBalance);assert.equal(m.shortPrevious+m.shortSell-m.shortBuy-m.shortRepay,m.shortBalance)}});
test('historical request reads the date-matched official snapshot and never calls current fundamentals',async()=>{const c=boot();c.stock={code:'8358',market:'TPEX'};c.assets={fetch:async r=>{assert.ok(r.url.endsWith('/chips/2026-10-06.json'));return Response.json(snapshot)}};const x=await vm.runInContext('extras(stock,"2026-10-06",true,assets)',c);assert.equal(x.institutional.foreign,-1156929);assert.equal(x.institutional.date,'2026-10-06');assert.equal(x.institutional.gross.foreign.buy,4557670);assert.equal(x.margin.marginBalance,26514);assert.equal(x.revenue,null);assert.equal(x.valuation,null);assert.equal(x.institutionalCost.value,null)});
test('missing institutional values stay missing, foreign dealer remains separate',()=>{const c=boot();c.o={'外陸資買賣超股數(不含外資自營商)':'1,500','外資自營商買賣超股數':'-500'};const i=vm.runInContext('institutionalFrom(o)',c);assert.equal(i.foreign,1500);assert.equal(i.foreignCombined,1000);assert.equal(i.trust,null);assert.equal(i.total,null);c.o={'證券代號':'1234'};assert.equal(vm.runInContext('institutionalFrom(o)',c),null)});
test('mismatched or undated response rejected, duplicate TWSE margin columns parsed by group',()=>{const c=boot();c.j={stat:'OK',date:'20261007',fields:['證券代號'],data:[['1234']]};assert.equal(vm.runInContext('datedChipRow(j,"1234","2026-10-06","TWSE","institutional")',c),null);delete c.j.date;assert.equal(vm.runInContext('datedChipRow(j,"1234","2026-10-06","TWSE","institutional")',c),null);c.j={stat:'OK',date:'20261006',tables:[{groups:[{title:'股票'},{title:'融資'}],fields:['代號','名稱','買進','賣出','現金償還','前日餘額','今日餘額','次一營業日限額','買進','賣出','現券償還','前日餘額','今日餘額','次一營業日限額','資券互抵','註記'],data:[['1234','例',4,2,1,10,11,100,1,3,0,2,4,100,0,'']]}]};const m=vm.runInContext('marginFrom(datedChipRow(j,"1234","2026-10-06","TWSE","margin"))',c);assert.equal(m.marginBalance,11);assert.equal(m.shortBalance,4)});
test('13 photograph foreign quantities match official data after lot display rounding',()=>{const c=boot(),refs=JSON.parse(fs.readFileSync('public/data/photo-references.json')).items;let count=0;for(const r of refs){if(r.visibleMetrics?.foreignNetLots==null)continue;c.o=snapshot.items.find(x=>x.code===r.code).institutional;const n=vm.runInContext('institutionalFrom(o).foreign',c);assert.equal(Math.sign(n)*Math.round(Math.abs(n)/1000),r.visibleMetrics.foreignNetLots,r.code);count++}assert.equal(count,13)});
test('19 research histories cover every trading session in their specified windows',()=>{const input=JSON.parse(fs.readFileSync('research/2026-10-06-full-photo-inputs.json')),calendar=JSON.parse(fs.readFileSync('public/data/trading-sessions.json')),refs=JSON.parse(fs.readFileSync('public/data/photo-references.json')).items;assert.equal(input.items.length,19);for(const x of input.items){const dates=x.rows.map(r=>r[0]),start=x.market==='TWSE'?'2025-09-01':'2026-05-01';assert.deepEqual(dates,calendar.sessions.filter(d=>d>=start&&d<='2026-10-06'),x.code);assert.equal(x.rows.at(-1)[4],refs.find(r=>r.code===x.code).current)}});
