const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const ctx=vm.createContext({Response,Request,URL,Headers,setTimeout,console});
vm.runInContext(fs.readFileSync('src/worker.js','utf8').replace('export default','globalThis.worker='),ctx);
function zone(price,type='pivotHigh',low=price,high=price){return {price,type,low,high,side:'resistance',score:3,sources:['前高／樞紐高'],age:5}}
function select(input){ctx.input={cur:100,tol:.0125,key:null,shelf:null,resist:[],cands:[],recentFloorLows:[],...input};return JSON.parse(JSON.stringify(vm.runInContext('selectPressureLevels(input)',ctx)))}
test('ordinary pressures are paired and retain known 255.5 / 265 shelf calculation',()=>{const first=zone(255.5,'shelf'),second=zone(265);const r=select({cur:250,shelf:first,resist:[first,second],recentFloorLows:[265]});assert.equal(r.firstResistance.price,255.5);assert.equal(r.secondResistance.price,265);assert.equal(r.mediumResistance,null);assert.equal(r.pressureMode,'ordinary')});
test('breakout preserves nearest independent second pressure below ten percent',()=>{const key=zone(168,'pivotHigh',167,169),mid=zone(185.5);const r=select({cur:160,key,resist:[key,zone(173),mid]});assert.equal(r.firstResistance,null);assert.equal(r.secondResistance.price,173);assert.equal(r.mediumResistance,null);assert.equal(r.pressureMode,'breakout')});
test('breakout without independent upper structure does not invent a second',()=>{const key=zone(105,'pivotHigh',104,108);const r=select({key,resist:[key,zone(108,'pivotHigh',107,109)]});assert.equal(r.firstResistance,null);assert.equal(r.secondResistance,null);assert.equal(r.mediumResistance,null)});
test('second pressure must be above first and outside its price band',()=>{const first=zone(106,'shelf',105,109);const r=select({shelf:first,resist:[first,zone(108,'pivotHigh',107,110),zone(114,'pivotHigh',112,115)]});assert.equal(r.secondResistance.price,114);assert.ok(r.secondResistance.low>r.firstResistance.high)});
test('one historical pressure does not fabricate a second or publish a lone first',()=>{const first=zone(105);const r=select({resist:[first],cands:[first]});assert.equal(r.firstResistance,null);assert.equal(r.secondResistance,null);assert.equal(r.pressureMode,'unconfirmed');assert.match(r.pressureNote,/待確認/)});
test('medium requires real structure, not a standalone moving average or round number',()=>{const key=zone(104);const r=select({key,resist:[key,zone(112,'round'),zone(114,'ma')]});assert.equal(r.mediumResistance,null)});
test('output classification obeys pressure invariants across historical and synthetic series',()=>{for(let seed=0;seed<20;seed++){ctx.rows=Array.from({length:100},(_,i)=>{const close=100+Math.sin(i*.43+seed)*12+Math.cos(i*.19)*8+i*(seed%3-1)*.1;return {date:new Date(Date.UTC(2026,0,i+1)).toISOString().slice(0,10),open:close-.4,close,high:close+2,low:close-2,volume:1000+(i%7)*300}});const a=vm.runInContext('analyze(rows)',ctx);if(a.breakout){assert.equal(a.resistance1,null);assert.equal(a.mediumResistance,null);if(a.resistance2)assert.ok(a.resistance2.bandLow>a.breakout.bandHigh)}else{assert.equal(Boolean(a.resistance1),Boolean(a.resistance2));if(a.resistance1)assert.ok(a.resistance2.bandLow>a.resistance1.bandHigh);assert.equal(a.mediumResistance,null)}}});
const ui=vm.createContext({localStorage:{getItem:()=>null,setItem:()=>{}},document:{querySelector:()=>null},console});
const app=fs.readFileSync('public/app.js','utf8');vm.runInContext(app.slice(0,app.indexOf('$("#analyze").onclick')),ui);
function html(a){ui.input=a;return vm.runInContext('pressureLevels(input).join("")',ui)}
function packed(price,distance=.05){return {price,bandLow:price,bandHigh:price,confidence:50,distance,sources:[]}}
test('touching intermediate bands are merged before selecting second pressure',()=>{const key=zone(105,'pivotHigh',104,108),middle=zone(110,'volume',108,112),upper=zone(114,'pivotHigh',112,115),next=zone(120);const r=select({key,resist:[key,middle,upper,next]});assert.equal(r.secondResistance.price,120);assert.equal(r.mediumResistance,null);assert.equal(r.firstResistance,null)});
test('merging is invariant to candidate order and duplicate observations',()=>{ctx.items=[zone(105,'pivotHigh',104,108),zone(110,'volume',108,112),zone(120)];const ordered=JSON.parse(JSON.stringify(vm.runInContext('mergePressureBands(items)',ctx)));ctx.items=[ctx.items[2],ctx.items[1],ctx.items[0],ctx.items[1]];const shuffled=JSON.parse(JSON.stringify(vm.runInContext('mergePressureBands(items)',ctx)));assert.deepEqual(shuffled.map(x=>[x.low,x.high]),ordered.map(x=>[x.low,x.high]));assert.deepEqual(ordered.map(x=>[x.low,x.high]),[[104,112],[120,120]])});
test('standalone moving averages and round numbers cannot bridge separate pressure structures',()=>{ctx.items=[zone(105,'pivotHigh',104,106),zone(110,'ma',106,114),zone(110,'round',106,114),zone(115,'volume',114,116)];const bands=JSON.parse(JSON.stringify(vm.runInContext('mergePressureBands(items)',ctx)));assert.equal(bands.length,2);assert.deepEqual(bands.map(x=>[x.low,x.high]),[[104,106],[114,116]])});
test('breakout UI shows second pressure and hides first and medium',()=>{const h=html({breakout:packed(105),resistance1:packed(108),resistance2:packed(110),mediumResistance:packed(115,.15)});assert.match(h,/關鍵突破／壓力共振區/);assert.match(h,/第二壓力/);assert.doesNotMatch(h,/class="label">第一壓力|class="label">中期壓力/)});
test('ordinary second stays labelled second even if distant',()=>{const h=html({resistance1:packed(105),resistance2:packed(120,.2)});assert.match(h,/第一壓力/);assert.match(h,/第二壓力/);assert.doesNotMatch(h,/中期壓力|關鍵突破/)});
test('incomplete ordinary pair is not rendered as a misleading lone level',()=>{assert.equal(html({resistance1:packed(105)}),'')});
test('historical request rejects months-old history instead of silently changing the base date',()=>{ctx.rows=[{date:'2025-12-31'}];assert.throws(()=>vm.runInContext('validateHistoryDates(rows,"2026-10-01")',ctx),/日期不完整/)});
test('latest analysis freshness check applies to TWSE as well as TPEX',()=>{ctx.rows=[{date:'2026-04-30'}];assert.throws(()=>vm.runInContext('validateHistoryDates(rows,null,"2026-10-06")',ctx),/過期/)});
test('prior trading session is accepted on weekends, future rows are rejected',()=>{ctx.rows=[{date:'2026-10-02'}];assert.doesNotThrow(()=>vm.runInContext('validateHistoryDates(rows,"2026-10-04")',ctx));assert.throws(()=>vm.runInContext('validateHistoryDates(rows,"2026-10-01")',ctx),/日期不完整/)});
const quote=['115/10/01','1,000','20,000','250','256','249','254','1','100'];
test('TWSE missing direct month falls back to official relay',async()=>{let calls=[];ctx.fetch=async url=>{calls.push(url);return new Response(JSON.stringify(calls.length===1?{stat:'查無資料'}:{stat:'OK',rows:[quote]}))};const rows=await vm.runInContext('twseMonth("1303",new Date("2026-10-01T12:00:00Z"))',ctx);assert.equal(rows[0].close,254);assert.equal(rows[0].date,'2026-10-01');assert.equal(calls.length,2);assert.match(calls[1],/twse\/month/)});
test('TWSE parser rejects a response from a different month',()=>{ctx.quote=quote;assert.equal(vm.runInContext('parseTwseMonth({stat:"OK",data:[quote]},"20260901").length',ctx),0)});
test('TWSE current direct month needs no relay request',async()=>{let calls=0;ctx.fetch=async()=>{calls++;return new Response(JSON.stringify({stat:'OK',data:[quote]}))};const rows=await vm.runInContext('twseMonth("2408",new Date("2026-10-01T12:00:00Z"))',ctx);assert.equal(rows.length,1);assert.equal(calls,1)});
