const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const ctx=vm.createContext({console,Response,Request,Headers,URL,setTimeout});
vm.runInContext(fs.readFileSync('src/worker.js','utf8').replace('export default','globalThis.worker='),ctx);
const reference=JSON.parse(fs.readFileSync('tests/references/2026-10-05.json'));
function run(rows){ctx.input=structuredClone(rows);return JSON.parse(JSON.stringify(vm.runInContext('deriveStructureLevels(input)',ctx)))}
function series(){return Array.from({length:80},(_,i)=>({date:new Date(Date.UTC(2026,5,i+1)).toISOString().slice(0,10),open:100,close:100,high:102,low:99,volume:1000}))}
test('25 cutoff snapshots match numeric anchors, absence and gap flags; one band remains unresolved',()=>{let priceMatches=0,bandMatches=0,stars=0;const differences=[];for(const item of reference.cases){const snap=JSON.parse(fs.readFileSync(`tests/fixtures/2026-10-05/${item.code}.json`));assert.ok(snap.rows.length>=65);assert.equal(snap.rows.at(-1).date,reference.baseDate);assert.ok(snap.rows.every(r=>r.date<=reference.baseDate));const a=run(snap.rows);for(const [key,e] of Object.entries(item.expected)){const p=a[key];if(!e){assert.equal(p,null);priceMatches++;bandMatches++;continue}assert.ok(p,`${item.code} ${key}`);assert.ok(p.price>=e.bandLow&&p.price<=e.bandHigh,`${item.code} ${key}`);priceMatches++;if(p.bandLow===e.bandLow&&p.bandHigh===e.bandHigh)bandMatches++;else differences.push(`${item.code}:${key}`);if(e.gapBoundary){assert.equal(p.gapBoundary,true);stars++}}}assert.equal(priceMatches,100);assert.equal(bandMatches,99);assert.equal(stars,9);assert.deepEqual(differences,['3004:resistance2'])});
test('unconfirmed last two bars cannot become pivot pressure',()=>{const rows=series();rows[78].high=105;assert.equal(run(rows).resistance1,null)});
test('a later close above a historical high consumes its ordinary pressure',()=>{const rows=series();rows[30].high=108;assert.equal(run(rows).resistance1.price,108);rows[40]={...rows[40],open:109,close:109,high:111,low:99};assert.notEqual(run(rows).resistance1?.price,108)});
test('old bars outside the 60-session window and structures outside 10 percent are excluded',()=>{const rows=series();rows[5].high=105;rows[30].high=120;assert.equal(run(rows).resistance1,null)});
test('confirmed high and independent unfilled gap create key confluence and independent medium pressure',()=>{const rows=series();rows[25].high=115;rows[34]={...rows[34],open:104.5,close:104.5,high:105,low:104};rows[35]={...rows[35],open:102,close:102,high:103,low:101};rows[40].high=103;const a=run(rows);assert.equal(a.breakout.price,103);assert.equal(a.resistance1,null);assert.equal(a.resistance2,null);assert.equal(a.mediumResistance.price,115);assert.equal(a.pressureMode,'breakout');rows[50].high=104;assert.equal(run(rows).breakout,null)});
test('same-anchor gap takes precedence and preserves pending-retest flag',()=>{const item=JSON.parse(fs.readFileSync('tests/fixtures/2026-10-05/2317.json'));const a=run(item.rows);assert.equal(a.support1.price,253.5);assert.equal(a.support1.bandHigh,253.5);assert.equal(a.support1.gapBoundary,true)});
test('Taiwan completion date excludes the current session before its close',()=>{assert.equal(vm.runInContext('latestCompletedDate(new Date("2026-10-05T20:43:00Z"))',ctx),'2026-10-05');assert.equal(vm.runInContext('latestCompletedDate(new Date("2026-10-06T06:01:00Z"))',ctx),'2026-10-06')});
