const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('src/worker.js','utf8');
class TaipeiMorning extends Date{constructor(...args){super(...(args.length?args:['2026-10-06T00:27:07Z']))}static now(){return Date.parse('2026-10-06T00:27:07Z')}}
function boot(fetch){const c=vm.createContext({console,Response,Request,Headers,URL,setTimeout,clearTimeout,Date:TaipeiMorning,fetch});vm.runInContext(source.replace('export default','globalThis.worker='),c);c.assets={fetch:async req=>{const p='public'+new URL(req.url).pathname;return fs.existsSync(p)?new Response(fs.readFileSync(p)):new Response('',{status:404})}};return c}
test('stock names and codes resolve from validated directory when live directory is offline',async()=>{let calls=0;const c=boot(async()=>{calls++;throw Error('offline')});for(const q of ['旺矽','6223']){c.q=q;const stock=await vm.runInContext('resolve(q,assets)',c);assert.equal(stock.code,'6223');assert.equal(stock.market,'TPEX');assert.equal(stock.name,'旺矽')}assert.equal(calls,0);assert.equal((await vm.runInContext('searchStocks("南亞",20,assets)',c))[0].code,'1303')});
test('pre-open October 6 uses completed October 5 data and explicit date notice with one history request',async()=>{let calls=0;const fixture=JSON.parse(fs.readFileSync('tests/fixtures/tpex-6223-2026-10-05.json'));const c=boot(async url=>{calls++;assert.match(url,/tpex\/range/);assert.match(url,/end=2026-10-05/);return new Response(JSON.stringify(fixture))});const r=await vm.runInContext('analyzeOne("旺矽","2026-10-06","standard",assets)',c);assert.equal(r.stock.code,'6223');assert.equal(r.analysis.date,'2026-10-05');assert.equal(r.analysis.current,5520);assert.equal(r.backtest.actual,null);assert.equal(r.backtest.requestedDate,'2026-10-06');assert.match(r.backtest.dateNote,/2026-10-06 尚無可用收盤資料/);assert.ok(r.analysis.rows.every(x=>x.date<='2026-10-05'));assert.equal(calls,1)});
test('range rejects another stock, malformed bars and future rows',()=>{const c=boot(async()=>{throw Error('offline')});c.j=JSON.parse(fs.readFileSync('tests/fixtures/tpex-6223-2026-10-05.json'));c.stock={code:'6223',market:'TPEX'};const n=vm.runInContext('parseTpexRange(j,stock,"2026-10-05").length',c);c.j.rows.push(['115/10/06',1,1,5500,5600,5400,5550],['115/10/04',1,1,5500,5000,5400,5550]);assert.equal(vm.runInContext('parseTpexRange(j,stock,"2026-10-05").length',c),n);c.j.code='8358';assert.equal(vm.runInContext('parseTpexRange(j,stock,"2026-10-05").length',c),0)});
test('empty monthly sources are each attempted once instead of nine repeat requests',async()=>{let calls=0;const c=boot(async()=>{calls++;return new Response(JSON.stringify({rows:[]}))});assert.equal((await vm.runInContext('tpexMonth("6223",new Date("2026-09-01"))',c)).length,0);assert.equal(calls,3)});
test('service failures keep HTTP context and never masquerade as a missing stock',async()=>{const box={textContent:'',classList:{remove(){}}},c=vm.createContext({console,clearTimeout,location:{origin:'https://example.test'},localStorage:{getItem:()=>null,setItem(){}},document:{querySelector:()=>box},fetch:async()=>new Response(JSON.stringify({success:false}),{status:503})});const s=fs.readFileSync('public/app.js','utf8');vm.runInContext(s.slice(0,s.indexOf('$("#analyze").onclick')),c);await assert.rejects(vm.runInContext('api({action:"search",q:"旺矽"})',c),/HTTP 503/);vm.runInContext('showSearchError(new Error("資料來源暫時無法連線"))',c);assert.match(box.textContent,/搜尋資料暫時無法取得/);assert.doesNotMatch(box.textContent,/找不到符合個股/)});
