import http from "node:http";
const PORT=process.env.PORT||10000;
const cache=new Map();
const send=(res,status,obj,ttl=300)=>{res.writeHead(status,{"content-type":"application/json;charset=UTF-8","cache-control":"public, max-age="+ttl,"access-control-allow-origin":"*"});res.end(JSON.stringify(obj))};
const fetchJson=async(url,referer)=>{const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 (compatible; TWStockConfluence/1.0)","accept":"application/json,text/plain,*/*","accept-language":"zh-TW,zh;q=0.9","referer":referer||"https://www.tpex.org.tw/"},redirect:"follow"});const text=await r.text();if(!r.ok)throw new Error("Official source HTTP "+r.status);try{return JSON.parse(text)}catch{throw new Error("Official source returned non-JSON")}};
const val=(o,keys)=>{for(const k of keys){if(o?.[k]!=null&&String(o[k]).trim())return String(o[k]).trim()}return""};
async function directory(market){const key="dir:"+market,h=cache.get(key);if(h&&Date.now()-h.t<3600000)return h.v;const urls=market==="TWSE"?["https://openapi.twse.com.tw/v1/opendata/t187ap03_L","https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL"]:["https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap03_O","https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes"];let map=new Map();for(const url of urls){try{const rows=await fetchJson(url,market==="TWSE"?"https://www.twse.com.tw/":"https://www.tpex.org.tw/");if(!Array.isArray(rows))continue;for(const x of rows){const code=val(x,["公司代號","證券代號","SecuritiesCompanyCode","SecuritiesCode","Code"]),name=val(x,["公司簡稱","證券名稱","公司名稱","CompanyAbbreviation","SecuritiesCompanyName","CompanyName","Name"]);if(!/^\d{4,6}[A-Z]?$/.test(code))continue;const prev=map.get(code);map.set(code,{Code:code,Name:name||prev?.Name||code,CompanyName:val(x,["公司名稱","CompanyName"])||prev?.CompanyName||name||code,Industry:val(x,["產業別","Industry"])||prev?.Industry||""})}}catch{}}const out=[...map.values()];if(out.length)cache.set(key,{t:Date.now(),v:out});return out}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://localhost");if(u.pathname==="/health")return send(res,200,{ok:true,source:"TWSE/TPEx official relay"},60);if(u.pathname==="/directory"){const market=(u.searchParams.get("market")||"").toUpperCase();if(!["TWSE","TPEX"].includes(market))return send(res,400,{error:"Invalid market"});const rows=await directory(market);return send(res,200,rows,300)}if(u.pathname!=="/tpex/month")return send(res,404,{error:"Not found"});const code=(u.searchParams.get("code")||"").trim(),date=(u.searchParams.get("date")||"").trim();if(!/^\d{4,6}[A-Z]?$/.test(code)||!/^\d{4}\/\d{2}\/01$/.test(date))return send(res,400,{error:"Invalid code/date"});const key=code+"|"+date,h=cache.get(key);if(h&&Date.now()-h.t<21600000)return send(res,200,h.v,300);const [yy,mm]=date.split("/"),roc=(Number(yy)-1911)+"/"+mm,urls=["https://www.tpex.org.tw/web/stock/aftertrading/daily_trading_info/st43_result.php?l=zh-tw&d="+encodeURIComponent(roc)+"&stkno="+encodeURIComponent(code),"https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock?code="+encodeURIComponent(code)+"&date="+encodeURIComponent(date)+"&response=json"];let j=null,arr=[];for(const official of urls){try{j=await fetchJson(official,"https://www.tpex.org.tw/");arr=j?.tables?.[0]?.data||j?.aaData||j?.data||[];if(Array.isArray(arr)&&arr.length)break}catch{}}const out={ok:true,source:"TPEx",code,date,rows:Array.isArray(arr)?arr:[],stat:j?.stat||null};if(out.rows.length)cache.set(key,{t:Date.now(),v:out});return send(res,200,out)}catch(e){return send(res,502,{ok:false,error:e.message||String(e)})}});
server.listen(PORT,()=>console.log("Official market relay listening on",PORT));
