const cache=new Map();
const UA="Mozilla/5.0 StockConfluenceV335/1.0";
async function getJson(url,ttl=300000,timeoutMs=15000){const h=cache.get(url);if(h&&Date.now()-h.t<ttl)return h.v;const r=await fetch(url,{signal:globalThis.AbortSignal?.timeout(timeoutMs),headers:{"user-agent":UA,accept:"application/json,text/plain,*/*"}});if(!r.ok)throw new Error(`資料來源回應 ${r.status}`);const v=await r.json();cache.set(url,{t:Date.now(),v});return v}
async function safeJson(url,ttl=300000){try{return await getJson(url,ttl,5000)}catch{return null}}
const num=v=>{if(v==null||v==="--"||v==="---"||v==="")return null;const n=Number(String(v).replace(/,/g,"").replace(/[+X]/g,"").replace(/%/g,""));return Number.isFinite(n)?n:null};
const norm=s=>String(s||"").replace(/[\s　()（）\-_/]/g,"").toLowerCase();
const pick=(o,names)=>{if(!o)return null;const ks=Object.keys(o);for(const n of names){const k=ks.find(x=>norm(x)===norm(n)||norm(x).includes(norm(n)));if(k!=null)return o[k]}return null};
const rocToISO=s=>{const m=String(s).trim().match(/(\d+)[\/.](\d+)[\/.](\d+)/);if(!m)return String(s);const y=+m[1],year=y<1911?y+1911:y;return `${year}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`};
const monthKey=d=>`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}01`,ymd=s=>String(s).replace(/-/g,"");
function taipeiDate(now=new Date()){return new Date(now.getTime()+8*3600000).toISOString().slice(0,10)}
function latestCompletedDate(now=new Date()){const local=new Date(now.getTime()+8*3600000);if(local.getUTCHours()*60+local.getUTCMinutes()<14*60+30)local.setUTCDate(local.getUTCDate()-1);while([0,6].includes(local.getUTCDay()))local.setUTCDate(local.getUTCDate()-1);return local.toISOString().slice(0,10)}
// Exact directory fields only: CompanyName must not match CompanyAbbreviation.
function directoryValue(row, keys){for(const key of keys){const found=Object.keys(row).find(k=>norm(k)===norm(key));const value=found==null?"":String(row[found]??"").trim();if(value)return value}return ""}
function directoryEntry(row,market){
 const code=directoryValue(row,["公司代號","證券代號","SecuritiesCompanyCode","SecuritiesCode","Code"]);
 if(!/^\d{4,6}[A-Z]?$/.test(code))return null;
 const abbr=directoryValue(row,["公司簡稱","CompanyAbbreviation"]),security=directoryValue(row,["證券名稱","SecuritiesCompanyName"]),generic=directoryValue(row,["Name"]),fullName=directoryValue(row,["公司名稱","CompanyName"]);
 const display=abbr||security||(generic&&!/股份有限公司|有限公司/.test(generic)?generic:"");
 return {code,name:display||code,fullName:fullName||generic||display||code,industry:directoryValue(row,["產業別","Industry"]),market,nameRank:abbr?3:security?2:display?1:0};
}
async function directory(){
 const key="DIR",h=cache.get(key);if(h&&Date.now()-h.t<3600000)return h.v;
 const urls=[["TWSE","https://openapi.twse.com.tw/v1/opendata/t187ap03_L"],["TPEX","https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap03_O"],["TWSE","https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL"],["TPEX","https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes"],["TWSE","https://tpex-official-relay.onrender.com/directory?market=TWSE"],["TPEX","https://tpex-official-relay.onrender.com/directory?market=TPEX"]];
 const settled=await Promise.allSettled(urls.map(x=>getJson(x[1],3600000))),map=new Map();
 for(let z=0;z<settled.length;z++){const res=settled[z];if(res.status!=="fulfilled"||!Array.isArray(res.value))continue;for(const row of res.value){const item=directoryEntry(row,urls[z][0]);if(!item)continue;const prev=map.get(item.code);map.set(item.code,prev?{...prev,name:item.nameRank>prev.nameRank?item.name:prev.name,nameRank:Math.max(item.nameRank,prev.nameRank),fullName:prev.fullName!==prev.code&&prev.fullName!==prev.name?prev.fullName:item.fullName,industry:prev.industry||item.industry}:item)}}
 const out=[...map.values()].map(({nameRank,...item})=>item);if(out.length)cache.set(key,{t:Date.now(),v:out});return out;
}
function rankStock(v,q){const nq=norm(q),nn=norm(v.name),nc=norm(v.code),nf=norm(v.fullName);if(nc===nq)return 1000;if(nn===nq)return 950;if(nf===nq)return 900;if(nc.startsWith(nq))return 850;if(nn.startsWith(nq))return 800;if(nn.includes(nq))return 600;if(nf.includes(nq))return 400;return 0}
async function bundledDirectory(assets){if(!assets)return[];try{const r=await assets.fetch(new Request("https://assets.local/data/stock-directory.json"));if(!r.ok)return[];const j=await r.json(),age=(new Date(taipeiDate()+"T00:00:00Z")-new Date(j.asOf+"T00:00:00Z"))/86400000;if(!Number.isFinite(age)||age<0||age>14||!Array.isArray(j.stocks))return[];return j.stocks.filter(s=>/^\d{4}$/.test(s.code)&&s.name&&["TWSE","TPEX"].includes(s.market))}catch{return[]}}
async function searchStocks(q,limit=20,assets){q=String(q||"").trim();if(!q)return[];const rank=d=>d.map(v=>({...v,_rank:rankStock(v,q)})).filter(v=>v._rank>0).sort((a,b)=>b._rank-a._rank||a.code.localeCompare(b.code)).slice(0,limit).map(({_rank,...v})=>v);const bundled=rank(await bundledDirectory(assets));return bundled.length?bundled:rank(await directory())}
async function resolve(q,assets){q=String(q||"").trim();if(!q)throw new Error("請輸入股票名稱或代碼");const matches=await searchStocks(q,20,assets);let x=matches.find(v=>v.code===q)||matches.find(v=>norm(v.name)===norm(q))||matches.find(v=>norm(v.fullName)===norm(q));if(!x&&matches.length===1)x=matches[0];if(!x&&matches.length>1)throw new Error(`「${q}」有多個符合個股，請從搜尋選項選擇`);if(!x&&/^\d{4,6}[A-Z]?$/.test(q)){const now=new Date(),tests=await Promise.allSettled([twseMonth(q,now),tpexMonth(q,now)]);if(tests[0].status==="fulfilled"&&tests[0].value.length)x={code:q,name:q,fullName:q,market:"TWSE"};else if(tests[1].status==="fulfilled"&&tests[1].value.length)x={code:q,name:q,fullName:q,market:"TPEX"}}if(!x)throw new Error(`找不到「${q}」；請從搜尋選項選擇個股`);return x}
function parseTwseMonth(j,date){if(j?.stat!=="OK")return[];const data=j.data||j.rows;if(!Array.isArray(data))return[];const month=date.slice(0,4)+"-"+date.slice(4,6);return data.map(r=>({date:rocToISO(r[0]),volume:num(r[1]),turnover:num(r[2]),open:num(r[3]),high:num(r[4]),low:num(r[5]),close:num(r[6]),trades:num(r[8])})).filter(x=>x.date.startsWith(month+"-")&&[x.open,x.high,x.low,x.close].every(v=>v!=null))}
async function twseMonth(code,d){const date=monthKey(d),urls=[`https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=${date}&stockNo=${encodeURIComponent(code)}&response=json`,`https://tpex-official-relay.onrender.com/twse/month?code=${encodeURIComponent(code)}&date=${date}`];for(const url of urls){try{const rows=parseTwseMonth(await getJson(url,3600000,8000),date);if(rows.length)return rows}catch{}}return[]}

const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function parseTpexResponse(r){if(!r.ok)throw new Error(`TPEx HTTP ${r.status}`);const j=await r.json(),arr=j?.rows||j?.tables?.[0]?.data||j?.aaData||j?.data||[];return Array.isArray(arr)?arr.map(x=>({date:rocToISO(String(x[0]||"").replace(/[＊*]/g,"")),volume:(num(x[1])||0)*1000,turnover:num(x[2])==null?null:num(x[2])*1000,open:num(x[3]),high:num(x[4]),low:num(x[5]),close:num(x[6]),trades:num(x[8])})).filter(x=>x.close!=null):[]}
async function tpexMonth(code,d){const ds=`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,"0")}/01`,headers={"user-agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1",accept:"application/json,text/plain,*/*","accept-language":"zh-TW,zh;q=0.9,en;q=0.8",referer:"https://www.tpex.org.tw/"},roc=`${d.getFullYear()-1911}/${String(d.getMonth()+1).padStart(2,"0")}`,urls=[`https://tpex-official-relay.onrender.com/tpex/month?code=${encodeURIComponent(code)}&date=${encodeURIComponent(ds)}`,`https://www.tpex.org.tw/web/stock/aftertrading/daily_trading_info/st43_result.php?l=zh-tw&d=${encodeURIComponent(roc)}&stkno=${encodeURIComponent(code)}`,`https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock?code=${encodeURIComponent(code)}&date=${encodeURIComponent(ds)}&response=json`];for(const url of urls){try{const rows=await parseTpexResponse(await fetch(url,{headers,signal:globalThis.AbortSignal?.timeout(8000)}));const filtered=rows.filter(r=>r.date.startsWith(ds.slice(0,7).replace("/","-")+"-")&&r.low>0&&r.low<=r.open&&r.open<=r.high&&r.low<=r.close&&r.close<=r.high);if(filtered.length)return filtered}catch{}}return[]}
async function tradingCalendar(cutoff,assets){
 if(!assets)return null;let calendar;try{const r=await assets.fetch(new Request("https://assets.local/data/trading-sessions.json"));if(r.ok)calendar=await r.json()}catch{}
 if(!calendar||!Array.isArray(calendar.sessions)||!/^\d{4}-\d{2}-\d{2}$/.test(calendar.coverageStart))return null;
 if(calendar.coverageEnd>=cutoff)return calendar;
 const current=await twseMonth("2330",new Date(cutoff+"T12:00:00Z"));if(!current.length)return null;
 return {...calendar,coverageEnd:cutoff,sessions:[...new Set([...calendar.sessions,...current.filter(r=>r.date<=cutoff).map(r=>r.date)])].sort()};
}
function parseTpexRange(j,stock,cutoff,calendar){
 if(j?.ok!==true||j.code!==stock.code||j.end!==cutoff||!Array.isArray(j.rows)||!calendar||calendar.coverageEnd<cutoff)return[];
 const sessions=new Set(calendar.sessions),seen=new Set(),out=[];
 for(const r of j.rows){if(!Array.isArray(r)||r.length<7)continue;const row={date:rocToISO(String(r[0]).replace(/[＊*]/g,"")),volume:num(r[1])==null?null:num(r[1])*1000,turnover:num(r[2])==null?null:num(r[2])*1000,open:num(r[3]),high:num(r[4]),low:num(r[5]),close:num(r[6]),trades:num(r[8])};if(row.date>cutoff)return[];if(row.date<calendar.coverageStart||!sessions.has(row.date))continue;if(![row.open,row.high,row.low,row.close,row.volume].every(Number.isFinite)||row.volume<0||row.low<=0||row.low>row.open||row.open>row.high||row.low>row.close||row.close>row.high)return[];if(seen.has(row.date))return[];seen.add(row.date);out.push(row)}return out.sort((a,b)=>a.date.localeCompare(b.date));
}
async function tpexRange(stock,cutoff,assets){try{const calendar=await tradingCalendar(cutoff,assets);if(!calendar)return[];const j=await getJson(`https://tpex-official-relay.onrender.com/tpex/range?code=${encodeURIComponent(stock.code)}&end=${encodeURIComponent(cutoff)}&v=3`,300000,18000);return parseTpexRange(j,stock,cutoff,calendar)}catch{return[]}}
async function history(s,months=14,endDate,assets){
 const cutoff=endDate||latestCompletedDate(),end=new Date(cutoff+"T12:00:00Z"),map=new Map();
 if(s.market==="TPEX"){const ranged=await tpexRange(s,cutoff,assets);if(ranged.length>=65)return ranged;months=Math.min(months,6)}
 const jobs=[];for(let i=months-1;i>=0;i--){const d=new Date(end.getFullYear(),end.getMonth()-i,1);jobs.push(s.market==="TPEX"?tpexMonth(s.code,d):twseMonth(s.code,d))}
 for(const z of await Promise.allSettled(jobs))if(z.status==="fulfilled")for(const r of z.value)if(r.date<=cutoff)map.set(r.date,r);
 return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date));
}

function levelCheck(level,actual,kind){if(!level||!actual)return null;const ref=kind==="support"?actual.low:actual.high,price=level.price,bandLow=level.bandLow??price,bandHigh=level.bandHigh??price,touched=actual.low<=price&&actual.high>=price,bandTouched=actual.low<=bandHigh&&actual.high>=bandLow,rangeGap=price<actual.low?actual.low-price:price>actual.high?price-actual.high:0;return{kind,price,bandLow,bandHigh,reference:ref,error:price-ref,errorPct:(price-ref)/ref,absError:Math.abs(price-ref),absErrorPct:Math.abs(price-ref)/ref,touched,bandTouched,rangeGap,rangeGapPct:rangeGap/price}}
const sma=(a,n,i,key="close")=>i<n-1?null:a.slice(i-n+1,i+1).reduce((s,z)=>s+(z[key]||0),0)/n;
function ema(v,n){const k=2/(n+1),o=[];let e=null;for(const x of v){e=e==null?x:x*k+e*(1-k);o.push(e)}return o}
function rsi(rows,n=14){if(rows.length<=n)return null;let g=0,l=0;for(let i=rows.length-n;i<rows.length;i++){const d=rows[i].close-rows[i-1].close;if(d>0)g+=d;else l-=d}return l===0?100:100-100/(1+(g/n)/(l/n))}
function stochastic(rows,n=9){if(rows.length<n)return{k:null,d:null};let K=50,D=50;for(let i=Math.max(n-1,rows.length-15);i<rows.length;i++){const w=rows.slice(i-n+1,i+1),hi=Math.max(...w.map(x=>x.high)),lo=Math.min(...w.map(x=>x.low)),rr=hi===lo?50:(rows[i].close-lo)/(hi-lo)*100;K=K*2/3+rr/3;D=D*2/3+K/3}return{k:K,d:D}}
function atr(rows,n=14){if(rows.length<n+1)return null;const tr=[];for(let i=1;i<rows.length;i++)tr.push(Math.max(rows[i].high-rows[i].low,Math.abs(rows[i].high-rows[i-1].close),Math.abs(rows[i].low-rows[i-1].close)));return tr.slice(-n).reduce((a,b)=>a+b,0)/n}
function std(vals){const m=vals.reduce((a,b)=>a+b,0)/vals.length;return Math.sqrt(vals.reduce((a,b)=>a+(b-m)**2,0)/vals.length)}
function obv(rows){let v=0;for(let i=1;i<rows.length;i++)v+=rows[i].close>rows[i-1].close?rows[i].volume:rows[i].close<rows[i-1].close?-rows[i].volume:0;return v}
function tickSize(p){return p<10?.01:p<50?.05:p<100?.1:p<500?.5:p<1000?1:5}
function volumeProfileNode(rows,cur){const data=rows.slice(-60),step=tickSize(cur),bins=new Map();for(const x of data){const lo=Math.floor(x.low/step)*step,hi=Math.ceil(x.high/step)*step,n=Math.max(1,Math.round((hi-lo)/step)+1),w=x.volume/n;for(let p=lo;p<=hi+step/10;p+=step){const k=Number(p.toFixed(4));bins.set(k,(bins.get(k)||0)+w)}}const below=[...bins.entries()].filter(([p])=>p<cur).sort((a,b)=>b[1]-a[1]||a[0]-b[0]);if(!below.length)return null;const [anchor,peak]=below[0];let low=anchor,n=0;for(let p=anchor-step;p>0&&n<5;p-=step,n++){const v=bins.get(Number(p.toFixed(4)))||0;if(v/peak<.65)break;low=Number(p.toFixed(4))}return{price:anchor,low,high:anchor}}
// Each candidate band already contains neighbors within the configured tolerance.
// Merge touching/overlapping bands before assigning their ordinal pressure labels.
function mergePressureBands(items){
 const ordered=items.filter(c=>c&&c.type!=="ma"&&c.type!=="round"&&Number.isFinite(c.price)&&Number.isFinite(c.low)&&Number.isFinite(c.high)&&c.low<=c.price&&c.price<=c.high).sort((a,b)=>a.low-b.low||a.high-b.high||a.price-b.price),groups=[];
 for(const c of ordered){const last=groups.at(-1);if(last&&c.low<=last.high){last.high=Math.max(last.high,c.high);last.members.push(c);last.sources=[...new Set([...last.sources,...(c.sources||[])])];last.score=Math.max(last.score||0,c.score||0)}else groups.push({...c,sources:[...(c.sources||[])],members:[c]})}
 return groups;
}
// Photo reconstruction hypothesis, not proof of the source system's formula.
// No reference prices, symbols or dates enter this calculation.
function derivePhotoPressure(rows,base){
 const end=rows.length-1,cur=rows[end].close,anchor=rows[end].high,tick=tickSize(anchor),A=atr(rows,14),lookback=120;
 const tolerance=A==null?null:Number((Math.ceil((A/2-1e-9)/tick)*tick).toFixed(4)),highs=[],closes=[];
 const policy={model:"photo-inferred",status:"推定公式；僅完成目前照片校準，尚未證實原公式",atrMethod:"14日True Range算術平均",atr14:A,tolerance,toleranceFactor:.5,lookbackSessions:lookback,pivotLeft:2,pivotRight:2};
 for(let i=Math.max(2,end-lookback+1);i<=end-2;i++){
  const neighbors=[rows[i-2],rows[i-1],rows[i+1],rows[i+2]];
  for(const [field,list] of [["high",highs],["close",closes]])if(neighbors.every(r=>rows[i][field]>=r[field])&&neighbors.some(r=>rows[i][field]>r[field]))list.push({price:rows[i][field],date:rows[i].date,index:i});
 }
 // Bound the whole band by the original anchor; do not extend the tolerance
 // repeatedly through a chain of intermediate candidates.
 const peers=highs.filter(p=>p.price>=anchor&&p.price-anchor<=tolerance+1e-9);
 if(!Number.isFinite(tolerance)||anchor<=cur||!peers.length)return {...base,photoPolicy:{...policy,matched:false},pressureNote:"照片推定模式未找到符合合併条件的結構；以下沿用既有壓力規則。"};
 const upper=Math.max(anchor,...peers.map(p=>p.price)),next=closes.filter(p=>p.price>upper).sort((a,b)=>b.index-a.index)[0]||null;
 const secondPeers=next?closes.filter(p=>p.price>upper&&Math.abs(p.price-next.price)<=tolerance+1e-9):[];
 const pack=(price,low,high,sources)=>({price,bandLow:low,bandHigh:high,distance:(price-cur)/cur,sources,score:3,confidence:null,strength:"推定結構"});
 const breakout=pack(anchor,anchor,upper,[`${rows[end].date}高點`,...peers.map(p=>`${p.date}已確認樞紐高點`)]);
 const resistance2=next?pack(next.price,Math.min(next.price,...secondPeers.map(p=>p.price)),Math.max(next.price,...secondPeers.map(p=>p.price)),[`${next.date}已確認收盤樞紐峰值`]):null;
 return {...base,breakout,resistance1:null,resistance2,resistance2Role:resistance2?"second":null,mediumResistance:null,pressureMode:"breakout",pressureNote:resistance2?"":"合併帶上方未找到已確認收盤峰值；第二壓力待確認。",photoPolicy:{...policy,matched:true,anchorDate:rows[end].date,upperSources:peers.map(p=>({date:p.date,price:p.price})),secondSource:next?{date:next.date,price:next.price}:null}};
}
// Breakout replaces the first pressure; the next independent structure remains second.
function selectPressureLevels({cur,tol,key,shelf,resist,cands,recentFloorLows}){
 if(key){
  const bands=mergePressureBands([key,...resist,...cands.filter(c=>c.side==="resistance")]),first=bands.find(b=>b.members.includes(key));
  if(first){key.low=first.low;key.high=first.high;key.sources=first.sources;key.score=first.score}
  const second=first?bands.find(b=>b.low>first.high)||null:null;
  return {firstResistance:null,secondResistance:second,mediumResistance:null,pressureMode:"breakout",pressureNote:second?"":"突破共振區上方未找到獨立第二壓力結構。"};
 }
 const first=shelf||resist[0]||null;
 if(!first)return {firstResistance:null,secondResistance:null,mediumResistance:null,pressureMode:"unconfirmed",pressureNote:"歷史資料尚未形成兩個獨立壓力區，第一／第二壓力待確認。"};
 const separate=c=>c!==first&&c.price>first.price*(1+tol)&&c.low>first.high;
 const floorPrice=recentFloorLows.find(p=>p>first.price*(1+tol)&&p>first.high);
 const floor=floorPrice?{price:floorPrice,low:floorPrice,high:floorPrice,score:2,sources:["近20日壓力帶下緣"],age:0}:null;
 const second=(shelf&&floor?floor:null)||resist.find(separate)||cands.filter(c=>c.side==="resistance"&&c.type!=="ma"&&c.type!=="round"&&separate(c)).sort((a,b)=>a.price-b.price)[0]||null;
 if(!second)return {firstResistance:null,secondResistance:null,mediumResistance:null,pressureMode:"unconfirmed",pressureNote:"僅找到一個壓力區，尚無更高的獨立第二壓力；第一／第二壓力待確認。"};
 return {firstResistance:first,secondResistance:second,mediumResistance:null,pressureMode:"ordinary",pressureNote:""};
}
// Support2 is a lower independent band; preserve original priority order.
function selectSecondSupport(first,raw,zones){
 if(!first)return null;
 const independent=c=>c&&c!==first&&Number.isFinite(c.price)&&c.price>0&&c.price<first.price&&c.price<first.low&&c.low<=c.price;
 return raw.find(c=>independent(c)&&c.type==="rangeLow"&&c.price>=first.price*.97)
  ||raw.find(c=>independent(c)&&c.price<=first.price*.982&&c.age<=40)
  ||raw.find(c=>independent(c)&&c.price<=first.price*.982)
  ||zones.find(independent)||null;
}
function analyze(rows){if(rows.length<65)throw new Error("歷史資料不足，至少需要 65 個交易日");const i=rows.length-1,cur=rows[i].close,prev=rows[i-1].close;rows.forEach((x,k)=>{x.ma5=sma(rows,5,k);x.ma10=sma(rows,10,k);x.ma20=sma(rows,20,k);x.ma60=sma(rows,60,k);x.avgVol20=k>=19?sma(rows,20,k,"volume"):null;x.volRatio=x.avgVol20?x.volume/x.avgVol20:null});
 const cands=[],add=(price,base,type,label,age=0)=>{if(price&&price>0)cands.push({price,base,type,label,age})};
 for(let j=2;j<rows.length-2;j++){const age=i-j;if(rows[j].high>rows[j-1].high&&rows[j].high>rows[j-2].high&&rows[j].high>rows[j+1].high&&rows[j].high>rows[j+2].high)add(rows[j].high,2,"pivotHigh",rows[j].high<cur?"前高轉支撐":"前高／樞紐高",age);if(rows[j].low<rows[j-1].low&&rows[j].low<rows[j-2].low&&rows[j].low<rows[j+1].low&&rows[j].low<rows[j+2].low){add(rows[j].low,2,"pivotLow","前低／樞紐低",age);if(rows[j].low>cur&&age<=20)add(rows[j].close,3,"shelf","前支撐轉壓力",age)}}
 for(let j=1;j<rows.length;j++){const age=i-j;if(rows[j].low>rows[j-1].high){add(rows[j].low,1,"gap","缺口上緣",age);add(rows[j-1].high,1,"gap","缺口下緣",age)}if(rows[j].volRatio>=(age===0?1.5:1.45)){add(rows[j].close,2,"volume","爆量K收盤",age);add(rows[j].low,1,"volume","爆量K低點",age);add(rows[j].high,1,"volume","爆量K高點",age)}}
 [["MA5",rows[i].ma5],["MA10",rows[i].ma10],["MA20",rows[i].ma20],["MA60",rows[i].ma60]].forEach(([l,p])=>add(p,1,"ma",String(l)));[5,10].forEach(step=>{add(Math.ceil(cur/step)*step,1,"round",`${step}元整數關卡`);add(Math.floor(cur/step)*step,1,"round",`${step}元整數關卡`)});
 const closes=rows.map(x=>x.close),ma13=sma(rows,13,i);add(ma13,1,"ma","MA13");const vp=volumeProfileNode(rows,cur);if(vp)add(vp.price,3,"volumeProfile","成交量密集區");const preLo20=Math.min(...rows.slice(-20).map(x=>x.low)),preLo60=Math.min(...rows.slice(-60).map(x=>x.low));add(preLo20,2,"rangeLow","近20日低點");add(preLo60,2,"rangeLow","近60日低點");for(let j=Math.max(0,i-59);j<=i;j++){const age=i-j;if(rows[j].volRatio>=1.5&&rows[j].close>preLo60&&(rows[j].close-preLo60)/preLo60<=.02)add(rows[j].close,1,"rangeLow","近60日低點",age)}
 const tol=.0125;cands.forEach(c=>{c.side=c.price<cur?"support":c.price>cur?"resistance":"current";const near=cands.filter(x=>x!==c&&(x.price<cur?"support":x.price>cur?"resistance":"current")===c.side&&Math.abs(x.price-c.price)/c.price<=tol);c.confluence=Math.min(near.length,5);c.score=c.base+c.confluence;c.sources=[...new Set([c.label,...near.map(x=>x.label)])];c.low=Math.min(c.price,...near.map(x=>x.price));c.high=Math.max(c.price,...near.map(x=>x.price));if(c.type==="volumeProfile"&&vp){c.low=vp.low;c.high=vp.high}});
 const zones=(arr,side)=>{const structural=s=>["爆量K收盤","爆量K低點","前高轉支撐","前低／樞紐低","缺口下緣","近20日低點","近60日低點"].includes(s),primary=arr.filter(c=>c.type!=="ma"&&c.type!=="round"&&!(c.type==="volumeProfile"&&!c.sources?.some(structural))),anchors=primary.length?primary:arr,ordered=[...anchors].sort((a,b)=>side==="support"?b.price-a.price:a.price-b.price),o=[];for(const c of ordered){if(o.some(x=>Math.abs(x.price-c.price)/cur<=tol))continue;o.push(c)}return o};
 const supportRaw=cands.filter(c=>c.side==="support"&&c.type!=="ma"&&c.type!=="round").sort((a,b)=>b.price-a.price),supportZones=zones(cands.filter(c=>c.side==="support"),"support"),vpCand=cands.find(c=>c.type==="volumeProfile"&&c.side==="support")||null,vpClose=vpCand&&Math.abs(vpCand.price-cur)/cur<=.03?cands.filter(c=>c.label==="爆量K收盤"&&c.side==="support"&&c.age<=40&&Math.abs(c.price-vpCand.price)/vpCand.price<=.005).sort((a,b)=>Math.abs(a.price-vpCand.price)-Math.abs(b.price-vpCand.price))[0]||null:null,s1=vpClose?(vpClose.price>vpCand.price?vpClose:vpCand):(supportZones[0]||null);if(s1?.label==="爆量K收盤"){const srcRow=[...rows].reverse().find(x=>x.close===s1.price&&x.volRatio>=(i-rows.indexOf(x)===0?1.5:1.45));if(srcRow)s1.low=Math.max(s1.low,srcRow.low)}
 const s2=selectSecondSupport(s1,supportRaw,supportZones),support2Note=s2?"":s1?"尚未找到低於第一支撐價格帶的獨立第二支撐，待確認。":"第一支撐結構不足，第二支撐待確認。";
 const resist=zones(cands.filter(c=>c.side==="resistance"),"resistance");
 const keyCandidates=cands.filter(c=>c.side==="resistance"&&(c.label==="缺口上緣"||c.type==="pivotHigh")&&(c.price-cur)/cur<=.04).sort((a,b)=>a.price-b.price),key=keyCandidates[0]||null,shelf=cands.filter(c=>c.side==="resistance"&&c.type==="shelf").sort((a,b)=>a.price-b.price)[0]||null,recentFloorLows=[...new Set(rows.slice(Math.max(0,i-20),i+1).map(x=>x.low).filter(p=>p>cur))].sort((a,b)=>a-b);
 const {firstResistance,secondResistance,mediumResistance,pressureMode,pressureNote}=selectPressureLevels({cur,tol,key,shelf,resist,cands,recentFloorLows});
 const e12=ema(closes,12),e26=ema(closes,26),mac=e12.map((v,k)=>v-e26[k]),sig=ema(mac,9),kd=stochastic(rows),A=atr(rows),w=closes.slice(-20),mid=w.reduce((a,b)=>a+b,0)/w.length,sd=std(w),bbU=mid+2*sd,bbL=mid-2*sd,confidence=c=>c?Math.max(1,Math.min(100,Math.round(35+c.score*8+Math.min(c.sources.length,4)*4-Math.min(Math.abs(c.price-cur)/cur*100,10)))):null,pack=(c,side,useUpper=false)=>c?{price:useUpper?c.high:c.price,bandLow:c.low,bandHigh:side==="support"?c.price:c.high,score:c.score,confidence:confidence(c),distance:((useUpper?c.high:c.price)-cur)/cur,sources:c.sources,strength:c.score>=6?"高共振":c.score>=4?"中共振":"一般"}:null;
 const hi20=Math.max(...rows.slice(-21,-1).map(x=>x.high)),lo20=Math.min(...rows.slice(-20).map(x=>x.low)),hi60=Math.max(...rows.slice(-61,-1).map(x=>x.high)),lo60=Math.min(...rows.slice(-60).map(x=>x.low)),volumeBreakout=cur>hi20&&rows[i].volRatio>=1.5,priceBreakout=cur>hi20,roc20=rows.length>20?cur/rows[i-20].close-1:null;let trendScore=0;if(cur>rows[i].ma5)trendScore++;else trendScore--;if(cur>rows[i].ma20)trendScore++;else trendScore--;if(rows[i].ma20>rows[i].ma60)trendScore++;else trendScore--;if(mac[i]>sig[i])trendScore++;else trendScore--;const trend=trendScore>=3?"偏多":trendScore<=-3?"偏空":"震盪";let tech=50+trendScore*7;const R=rsi(rows);if(R!=null&&R>=55&&R<=75)tech+=7;else if(R!=null&&R<40)tech-=7;if(rows[i].volRatio>=1.5)tech+=cur>=prev?6:-6;if(volumeBreakout)tech+=8;tech=Math.max(0,Math.min(100,Math.round(tech)));
 return{current:cur,previous:prev,change:cur-prev,changePct:(cur-prev)/prev,date:rows[i].date,open:rows[i].open,high:rows[i].high,low:rows[i].low,volume:rows[i].volume,turnover:rows[i].turnover,trades:rows[i].trades,volumeRatio:rows[i].volRatio,ma5:rows[i].ma5,ma10:rows[i].ma10,ma13,ma20:rows[i].ma20,ma60:rows[i].ma60,rsi14:R,k:kd.k,d:kd.d,macd:mac[i],signal:sig[i],histogram:mac[i]-sig[i],atr14:A,atrPct:A==null?null:A/cur,bollMid:mid,bollUpper:bbU,bollLower:bbL,trend,trendScore,technicalScore:tech,high20:hi20,low20:lo20,high60:hi60,low60:lo60,roc20,drawdown20:cur/hi20-1,priceBreakout,volumeBreakout,obv:obv(rows.slice(-60)),support1:pack(s1,"support"),support2:pack(s2,"support"),support2Note,breakout:pack(key,"resistance"),resistance1:pack(firstResistance,"resistance"),resistance2:pack(secondResistance,"resistance"),resistance2Role:secondResistance?"second":null,mediumResistance:pack(mediumResistance,"resistance"),pressureMode,pressureNote,tolerance:tol,rows:rows.slice(-120)}}
function rowObject(j,code){if(!j)return null;if(Array.isArray(j))return j.find(x=>String(pick(x,["股票代號","證券代號","SecuritiesCompanyCode","SecuritiesCode","Code"])||"").trim()===code)||null;for(const t of j.tables||[]){const fields=t.fields||[],data=t.data||[],idx=fields.findIndex(x=>/股票代號|證券代號|代號/.test(x));if(idx>=0){const r=data.find(x=>String(x[idx]).trim()===code);if(r)return Object.fromEntries(fields.map((f,k)=>[f,r[k]]))}}if(Array.isArray(j.data)&&Array.isArray(j.fields)){const idx=j.fields.findIndex(x=>/股票代號|證券代號|代號/.test(x)),r=j.data.find(x=>String(x[idx]).trim()===code);if(r)return Object.fromEntries(j.fields.map((f,k)=>[f,r[k]]))}return null}
function institutionalFrom(o){if(!o)return null;const foreign=(num(pick(o,["外陸資買賣超股數(不含外資自營商)","外陸資買賣超股數","ForeignInvestorsIncludeMainlandAreaInvestors-Difference","ForeignInvestorsDifference"]))||0)+(num(pick(o,["外資自營商買賣超股數","ForeignDealersDifference"]))||0),trust=num(pick(o,["投信買賣超股數","SecuritiesInvestmentTrustCompanies-Difference","InvestmentTrustDifference"])),dealer=num(pick(o,["自營商買賣超股數","Dealers-Difference","DealerDifference"])),total=num(pick(o,["三大法人買賣超股數","TotalDifference"]));return{foreign,trust,dealer,total:total??((foreign||0)+(trust||0)+(dealer||0))}}
function marginFrom(o){if(!o)return null;return{marginBalance:num(pick(o,["融資今日餘額","MarginPurchaseTodayBalance","MarginPurchaseBalance"])),shortBalance:num(pick(o,["融券今日餘額","ShortSaleTodayBalance","ShortSaleBalance"]))}}
function valuationFrom(o){if(!o)return null;return{pe:num(pick(o,["本益比","PEratio","PriceEarningRatio"])),pb:num(pick(o,["股價淨值比","PBratio","PriceBookRatio"])),yield:num(pick(o,["殖利率(%)","殖利率","DividendYield"]))}}
function revenueFrom(o){if(!o)return null;return{month:String(pick(o,["資料年月","RevenueYearMonth","YearMonth"])||""),revenue:num(pick(o,["營業收入-當月營收","當月營收","CurrentMonthRevenue"])),mom:num(pick(o,["營業收入-上月比較增減(%)","上月比較增減(%)","MoM"])),yoy:num(pick(o,["營業收入-去年同月增減(%)","去年同月增減(%)","YoY"]))}}
async function extras(stock,date){const code=stock.code,ds=ymd(date);let inst=null,margin=null,val=null,rev=null;if(stock.market==="TWSE"){const [ij,mj,vj,rj]=await Promise.all([safeJson(`https://www.twse.com.tw/rwd/zh/fund/T86?date=${ds}&selectType=ALLBUT0999&response=json`,1800000),safeJson(`https://www.twse.com.tw/rwd/zh/marginTrading/MI_MARGN?date=${ds}&selectType=ALL&response=json`,1800000),safeJson("https://openapi.twse.com.tw/v1/exchangeReport/BWIBBU_ALL",3600000),safeJson("https://openapi.twse.com.tw/v1/opendata/t187ap05_L",3600000)]);inst=institutionalFrom(rowObject(ij,code));margin=marginFrom(rowObject(mj,code));val=valuationFrom(rowObject(vj,code));rev=revenueFrom(rowObject(rj,code))}else{const [ij,mj,vj,rj]=await Promise.all([safeJson("https://www.tpex.org.tw/openapi/v1/tpex_3insti_daily_trading",1800000),safeJson("https://www.tpex.org.tw/openapi/v1/tpex_margin_balance",1800000),safeJson("https://www.tpex.org.tw/openapi/v1/tpex_mainboard_peratio_analysis",3600000),safeJson("https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap05_O",3600000)]);inst=institutionalFrom(rowObject(ij,code));margin=marginFrom(rowObject(mj,code));val=valuationFrom(rowObject(vj,code));rev=revenueFrom(rowObject(rj,code))}return{institutional:inst,margin,valuation:val,revenue:rev,status:{institutional:!!inst,margin:!!margin,valuation:!!val,revenue:!!rev}}}
function composite(a,e){let chip=50;if(e.institutional)for(const x of[e.institutional.foreign,e.institutional.trust,e.institutional.dealer])if(x!=null)chip+=x>0?8:x<0?-8:0;chip=Math.max(0,Math.min(100,Math.round(chip)));let fund=50;if(e.revenue?.yoy!=null)fund+=Math.max(-20,Math.min(20,e.revenue.yoy/2));if(e.revenue?.mom!=null)fund+=Math.max(-10,Math.min(10,e.revenue.mom/2));fund=Math.max(0,Math.min(100,Math.round(fund)));const score=Math.round(a.technicalScore*.6+chip*.25+fund*.15);return{technical:a.technicalScore,chip,fundamental:fund,structure:score,label:score>=65?"結構偏強":score<=35?"結構偏弱":"中性整理",note:"分數是資料結構整理，不是買賣建議；缺少籌碼或營收資料時以中性值計。"}}
function validateHistoryDates(rows,asOf,today=new Date().toISOString().slice(0,10)){
 const latest=rows.at(-1)?.date||"",reference=asOf||today;
 const gap=latest?(new Date(reference+"T12:00:00Z")-new Date(latest+"T12:00:00Z"))/86400000:Infinity;
 if(!Number.isFinite(gap)||gap<0||gap>10)throw new Error(`歷史行情日期不完整：要求基準日 ${reference}，實際最新資料 ${latest||"無資料"}；已停止使用過期資料計算，請稍後重試。`);
}
async function archivedHistory(stock,asOf,assets){
 if(!assets||!asOf)return null;
 try{const r=await assets.fetch(new Request(`https://assets.local/data/history/${asOf}/${stock.code}.json`));if(!r.ok)return null;const j=await r.json();if(j.code!==stock.code||j.market!==stock.market||j.baseDate!==asOf||!Array.isArray(j.rows)||j.rows.length<65)return null;let prev="";for(const row of j.rows){if(!/^\d{4}-\d{2}-\d{2}$/.test(row.date)||row.date<=prev||row.date>asOf||![row.open,row.high,row.low,row.close,row.volume].every(Number.isFinite)||row.volume<0||row.low<=0||row.low>row.open||row.open>row.high||row.low>row.close||row.close>row.high)return null;prev=row.date}return prev===asOf?j:null}catch{return null}
}
async function analyzeOne(q,asOf,assets,model="standard"){if(!["standard","photo-inferred"].includes(model))throw new Error("無效的位點模式");if(asOf&&asOf>taipeiDate())throw new Error("回測日期不能晚於今天");const stock=await resolve(q,assets);const archive=await archivedHistory(stock,asOf||latestCompletedDate(),assets);let rows,actualNext=null;if(archive){rows=archive.rows}else if(asOf){const end=new Date(asOf+"T12:00:00");end.setDate(end.getDate()+31);const validationEnd=[end.toISOString().slice(0,10),latestCompletedDate()].sort()[0];const all=await history(stock,15,validationEnd,assets);rows=all.filter(x=>x.date<=asOf);actualNext=all.find(x=>x.date>asOf)||null}else rows=await history(stock,14,latestCompletedDate(),assets);if(rows.length<65)throw new Error(`${stock.market} ${stock.code} 歷史行情僅取得 ${rows.length} 個交易日（基準日 ${asOf||"最新"}），未達 65 日；請稍後重試`);validateHistoryDates(rows,asOf||latestCompletedDate());let analysis;try{analysis=analyze(rows);if(model==="photo-inferred")analysis=derivePhotoPressure(rows,analysis)}catch(e){throw new Error(`位點計算失敗 ${stock.code}：${e?.message||e}`)}if(analysis.breakout)analysis.resistance1=null;const historical=!!asOf,extra=historical?{institutional:null,margin:null,valuation:null,revenue:null,status:{institutional:false,margin:false,valuation:false,revenue:false}}:await extras(stock,analysis.date),score=composite(analysis,extra),checks=historical&&actualNext?{support1:levelCheck(analysis.support1,actualNext,"support"),support2:levelCheck(analysis.support2,actualNext,"support"),breakout:levelCheck(analysis.breakout,actualNext,"breakout"),resistance1:levelCheck(analysis.resistance1,actualNext,"resistance"),resistance2:levelCheck(analysis.resistance2,actualNext,"resistance"),mediumResistance:levelCheck(analysis.mediumResistance,actualNext,"resistance")}:null,checkList=checks?Object.values(checks).filter(Boolean):[],maePct=checkList.length?checkList.reduce((s,x)=>s+x.absErrorPct,0)/checkList.length:null,bandHitRate=checkList.length?checkList.filter(x=>x.bandTouched).length/checkList.length:null;return{stock,analysis,extra,score,backtest:historical?{requestedDate:asOf,baseDate:analysis.date,predictionFor:actualNext?.date||null,usedRows:rows.length,noLookahead:true,actual:actualNext?{date:actualNext.date,open:actualNext.open,high:actualNext.high,low:actualNext.low,close:actualNext.close}:null,checks,maePct,bandHitRate}:null,source:archive?`${stock.market=== "TPEX"?"TPEx":"TWSE"}歷史行情快照（截至 ${archive.baseDate}；隔日實績尚未載入）`:stock.market==="TWSE"?"臺灣證券交易所 TWSE":"證券櫃檯買賣中心 TPEx",version:"3.3.44.6"}}
async function scanStocks(raw,assets,asOf,model="standard"){const codes=[...new Set(String(raw||"").split(/[\s,，;；]+/).map(x=>x.trim()).filter(Boolean))].slice(0,12);if(!codes.length)throw new Error("請輸入至少一檔股票代碼或名稱");if(codes.length>1)throw new Error("掃描已改為逐檔獨立請求；請重新整理至最新版後再開始掃描。");const jobs=codes.map(async q=>{try{const {stock,analysis,extra,score}=await analyzeOne(q,asOf,assets,model),supportGap=analysis.support1?Math.abs(analysis.support1.distance):null,breakoutGap=analysis.breakout?analysis.breakout.distance:null,inst=extra.institutional||{},tags=[];if(supportGap!=null&&supportGap<=.015)tags.push("接近支撐");if(breakoutGap!=null&&breakoutGap>=0&&breakoutGap<=.02)tags.push("接近突破");if(analysis.volumeBreakout)tags.push("量價突破");if((inst.foreign||0)>0&&(inst.trust||0)>0)tags.push("外投同買");if((inst.total||0)>0)tags.push("法人偏多");if(analysis.trend==="偏多")tags.push("技術偏多");if(score.structure>=70)tags.push("高共振");let observation=score.structure+(tags.includes("接近支撐")?6:0)+(tags.includes("接近突破")?6:0)+(tags.includes("量價突破")?8:0)+(tags.includes("外投同買")?5:0);observation=Math.max(0,Math.min(100,Math.round(observation)));return{ok:true,stock,date:analysis.date,current:analysis.current,changePct:analysis.changePct,trend:analysis.trend,structure:score.structure,observation,support:analysis.support1?{price:analysis.support1.price,distance:analysis.support1.distance,confidence:analysis.support1.confidence}:null,breakout:analysis.breakout?{price:analysis.breakout.price,distance:analysis.breakout.distance,confidence:analysis.breakout.confidence}:null,volumeRatio:analysis.volumeRatio,tags}}catch(e){return{ok:false,query:q,error:e.message||String(e)}}});const results=await Promise.all(jobs);return results.sort((a,b)=>(b.ok?b.observation:-1)-(a.ok?a.observation:-1))}
async function engine(input,assets){if(input.action==="analyze")return analyzeOne(input.q||"",input.asOf,assets,input.model||"standard");if(input.action==="scan")return{results:await scanStocks(input.codes||"",assets,input.asOf,input.model||"standard"),version:"3.3.44.6"};return{results:await searchStocks(input.q||"",20,assets),version:"3.3.44.6"}}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==="/api/stock"){if(request.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:{"content-type":"application/json"}});try{const input=await request.json();if(!["analyze","scan","search"].includes(input.action))throw new Error("無效操作");if(input.asOf&&!/^\d{4}-\d{2}-\d{2}$/.test(input.asOf))throw new Error("日期格式錯誤");const out=await engine(input,env.ASSETS);return new Response(JSON.stringify(out),{headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}})}catch(e){return new Response(JSON.stringify({error:e?.message||"分析失敗"}),{status:400,headers:{"content-type":"application/json;charset=UTF-8"}})}}const asset=await env.ASSETS.fetch(request);const headers=new Headers(asset.headers);if(["/","/index.html","/app.js","/styles.css","/sw.js"].includes(u.pathname))headers.set("cache-control","no-store, no-cache, must-revalidate, max-age=0");return new Response(asset.body,{status:asset.status,statusText:asset.statusText,headers})}};
